#!/bin/sh
# Prepare a NUX example QEMU/GDB debugging session from an out-of-tree build.
#
# The helper mirrors the existing example `make qemu_dbg` flow: it builds the
# architecture-specific APXH/example image, writes a GDB command file that loads
# kernel symbols and connects to QEMU's default `-s` stub on :1234, then prints
# the exact QEMU and GDB commands to run.  GDB is not required unless the caller
# runs the printed command.
#
# Environment:
#   ARCH              Architecture to debug: i386, amd64, or riscv64 (required).
#   TOOLBIN           Optional toolchain bin directory prepended to PATH.
#   TOOLCHAIN         Optional target tool prefix; amd64 defaults to the local
#                     smoke override x86_64-linux-gnu unless set explicitly.
#   TOOLCHAIN32       Optional amd64 APXH multiboot 32-bit prefix; default
#                     i686-unknown-elf.
#   BUILD/NUX_BUILD   Optional out-of-tree build directory. Defaults under /tmp.
#   JOBS              make parallelism, default nproc or 1.
#   TIMEOUT           QEMU debug timeout seconds for --run-qemu, default 30.
#   GDB               GDB command to print, default gdb or gdb-multiarch.
#   GDB_CMDS          GDB command-file path, default $BUILD/gdb-$ARCH-qemu-debug.gdb.
#   QEMU_LOG          QEMU log for --run-qemu, default $BUILD/qemu-$ARCH-debug.log.
#   NUX_SRCDIR        Source checkout path, default parent of this script's tools/ dir.
#   NUX_SMOKE_REUSE_BUILD=1 or NUX_DEBUG_REUSE_BUILD=1 allows non-empty BUILD.
#   NUX_DEBUG_PREPARE_ONLY=1 suppresses QEMU launch even with --run-qemu.

set -eu

prog=${0##*/}
run_qemu=0
do_build=1

usage() {
    cat <<'EOF'
Usage: tools/qemu-debug.sh --prepare
       tools/qemu-debug.sh --run-qemu

Prepare a NUX example debug build and write a GDB command file for the existing
`make qemu_dbg` flow. Select the target with ARCH=i386, ARCH=amd64, or
ARCH=riscv64.

Modes:
  --prepare   Configure/build example_qemu, write the GDB command file, and
              print the QEMU/GDB commands. This is the default mode and does
              not require GDB or launch QEMU.
  --run-qemu  Do --prepare, then run `make qemu_dbg` under timeout. Because
              qemu_dbg uses -S -s, timeout rc 124 is expected diagnostic
              evidence that QEMU paused for a debugger.
  --help      Show this help.

Common examples:
  ARCH=riscv64 BUILD=/tmp/the-nux-riscv64-debug ./tools/qemu-debug.sh --prepare
  TOOLBIN=/path/to/i686/bin ARCH=i386 ./tools/qemu-debug.sh --prepare
  TOOLBIN=/path/to/i686/bin ARCH=amd64 TOOLCHAIN=x86_64-linux-gnu \
    TOOLCHAIN32=i686-unknown-elf ./tools/qemu-debug.sh --prepare
EOF
}

note() {
    echo "$prog: $*"
}

die() {
    echo "$prog: error: $*" >&2
    exit 1
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found on PATH: $1"
}

run_make_step() {
    subdir=$1
    shift
    note "running make -j$JOBS -C $subdir $*"
    {
        echo
        echo "### make -j$JOBS -C $subdir $*"
    } >>"$make_log"
    if ! (cd "$builddir" && make -j"$JOBS" -C "$subdir" "$@" >>"$make_log" 2>&1); then
        tail -n 160 "$make_log" >&2 || true
        die "make -C $subdir $* failed; see $make_log"
    fi
}

write_gdb_cmds() {
    cat >"$gdb_cmds" <<EOF
# Generated by tools/qemu-debug.sh for ARCH=$arch.
# Start QEMU separately with the printed qemu_dbg command, then run:
#   $gdb_prog -x $gdb_cmds
#
# The example Makefile's qemu_dbg target adds -S -s, so QEMU starts paused and
# exposes the default GDB stub on TCP port 1234.
set confirm off
set pagination off
set print pretty on

# Load the NUX example kernel ELF symbols.  This does not require GDB to be
# installed while preparing the build; it is consumed only when you run GDB.
file $kernel_elf

# APXH boot-loader symbols are often useful before the kernel payload is
# entered.  Uncomment if you want APXH symbols as additional context.
# add-symbol-file $apxh_elf

# The user payload is loaded by the example kernel at a runtime user virtual
# address.  Uncomment only after determining the load address for your session.
# add-symbol-file $user_elf <user-payload-load-vaddr>

# Connect to QEMU's -s / qemu_dbg stub.
target remote :1234

# Optional next step once breakpoints are installed:
# continue
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --prepare)
            run_qemu=0
            do_build=1
            shift
            ;;
        --run-qemu)
            run_qemu=1
            do_build=1
            shift
            ;;
        --print)
            # Print/write commands for an already prepared build.  This mode is
            # intentionally non-building; --prepare is the verification mode.
            do_build=0
            run_qemu=0
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "unexpected argument: $1"
            ;;
    esac
done

if [ "${NUX_DEBUG_PREPARE_ONLY:-0}" = "1" ]; then
    run_qemu=0
fi

arch=${ARCH:-}
[ -n "$arch" ] || die "select an architecture with ARCH=i386|amd64|riscv64"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
srcdir=${NUX_SRCDIR:-$(CDPATH= cd -- "$script_dir/.." && pwd -P)}
srcdir=$(CDPATH= cd -- "$srcdir" && pwd -P) || die "cannot resolve source directory"
[ -x "$srcdir/configure" ] || die "configure not found/executable in source directory: $srcdir"
[ -f "$srcdir/example/Makefile.in" ] || die "example/Makefile.in not found in source directory: $srcdir"

if [ -n "${TOOLBIN:-}" ]; then
    [ -d "$TOOLBIN" ] || die "TOOLBIN does not name a directory: $TOOLBIN"
    toolbin_abs=$(CDPATH= cd -- "$TOOLBIN" && pwd -P) || die "cannot resolve TOOLBIN: $TOOLBIN"
    PATH="$toolbin_abs:$PATH"
    export PATH
fi

case "$arch" in
    i386)
        tool_prefix=${TOOLCHAIN:-i686-unknown-elf}
        qemu_cmd=qemu-system-i386
        hal_dir=libhal_x86
        plt_dir=libplt_acpi
        apxh_dir=apxh/multiboot
        apxh_elf_subpath=apxh/multiboot/apxh
        default_gdb=gdb
        configure_tool_args="ARCH=i386"
        if [ -n "${TOOLCHAIN:-}" ]; then
            configure_tool_args="$configure_tool_args TOOLCHAIN=$TOOLCHAIN"
        fi
        ;;
    amd64)
        TOOLCHAIN=${TOOLCHAIN:-x86_64-linux-gnu}
        TOOLCHAIN32=${TOOLCHAIN32:-i686-unknown-elf}
        export TOOLCHAIN TOOLCHAIN32
        tool_prefix=$TOOLCHAIN
        qemu_cmd=qemu-system-x86_64
        hal_dir=libhal_x86
        plt_dir=libplt_acpi
        apxh_dir=apxh/multiboot
        apxh_elf_subpath=apxh/multiboot/apxh
        default_gdb=gdb
        configure_tool_args="ARCH=amd64 TOOLCHAIN=$TOOLCHAIN TOOLCHAIN32=$TOOLCHAIN32"
        ;;
    riscv64)
        tool_prefix=${TOOLCHAIN:-riscv64-unknown-elf}
        qemu_cmd=qemu-system-riscv64
        hal_dir=libhal_riscv
        plt_dir=libplt_sbi
        apxh_dir=apxh/sbi
        apxh_elf_subpath=apxh/sbi/apxh
        default_gdb=gdb-multiarch
        configure_tool_args="ARCH=riscv64"
        if [ -n "${TOOLCHAIN:-}" ]; then
            configure_tool_args="$configure_tool_args TOOLCHAIN=$TOOLCHAIN"
        fi
        ;;
    *)
        die "unsupported ARCH=$arch (supported: i386, amd64, riscv64)"
        ;;
esac

gdb_prog=${GDB:-$default_gdb}

require_cmd make
if [ "$run_qemu" -eq 1 ]; then
    require_cmd timeout
    require_cmd "$qemu_cmd"
fi
for suffix in gcc ld ar objcopy; do
    require_cmd "$tool_prefix-$suffix"
done
if [ "$arch" = amd64 ]; then
    require_cmd "$TOOLCHAIN32-gcc"
fi

if [ -n "${BUILD:-}" ]; then
    build_input=$BUILD
elif [ -n "${NUX_BUILD:-}" ]; then
    build_input=$NUX_BUILD
else
    build_input=${TMPDIR:-/tmp}/the-nux-$arch-debug-$$
fi

build_parent=$(dirname -- "$build_input")
build_base=$(basename -- "$build_input")
mkdir -p "$build_parent"
build_parent=$(CDPATH= cd -- "$build_parent" && pwd -P) || die "cannot resolve build parent: $build_parent"
builddir=$build_parent/$build_base

case "$builddir/" in
    "$srcdir/"*) die "BUILD must be outside the source checkout; got $builddir" ;;
esac

if [ "$do_build" -eq 1 ] && [ -d "$builddir" ] && [ "$(find "$builddir" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]; then
    if [ "${NUX_SMOKE_REUSE_BUILD:-0}" != "1" ] && [ "${NUX_DEBUG_REUSE_BUILD:-0}" != "1" ]; then
        die "BUILD exists and is not empty: $builddir (choose a fresh directory or set NUX_SMOKE_REUSE_BUILD=1)"
    fi
fi
mkdir -p "$builddir"

if git -C "$srcdir" submodule status --recursive >/dev/null 2>&1; then
    if git -C "$srcdir" submodule status --recursive | grep -q '^-'; then
        echo "$prog: warning: source checkout has uninitialized submodules; run git submodule update --init --recursive in this worktree if configure/build fails" >&2
    fi
fi

if [ -z "${JOBS:-}" ]; then
    if command -v nproc >/dev/null 2>&1; then
        JOBS=$(nproc)
    else
        JOBS=1
    fi
fi
TIMEOUT=${TIMEOUT:-30}
configure_log=${CONFIGURE_LOG:-$builddir/configure-$arch-debug.log}
make_log=${MAKE_LOG:-$builddir/make-$arch-debug.log}
qemu_log=${QEMU_LOG:-${LOG:-$builddir/qemu-$arch-debug.log}}
gdb_cmds=${GDB_CMDS:-$builddir/gdb-$arch-qemu-debug.gdb}

kernel_elf=$builddir/example/kern/example
user_elf=$builddir/example/user/exuser
apxh_elf=$builddir/$apxh_elf_subpath
example_img=$builddir/example/example_qemu

note "source: $srcdir"
note "build: $builddir"
if [ -n "${TOOLBIN:-}" ]; then
    note "toolbin: $toolbin_abs"
else
    note "toolbin: not set; using target tools already on PATH"
fi
note "ARCH=$arch"
note "target tool prefix: $tool_prefix"
if [ "$arch" = amd64 ]; then
    note "amd64 APXH multiboot 32-bit prefix: $TOOLCHAIN32"
fi
note "configure log: $configure_log"
note "make log: $make_log"
note "GDB command file: $gdb_cmds"

if [ "$do_build" -eq 1 ]; then
    note "running configure $configure_tool_args"
    # shellcheck disable=SC2086 # configure_tool_args is intentionally split like make variables.
    if ! (cd "$builddir" && "$srcdir/configure" $configure_tool_args >"$configure_log" 2>&1); then
        tail -n 100 "$configure_log" >&2 || true
        die "configure failed; see $configure_log"
    fi

    : >"$make_log"
    if [ "$arch" = riscv64 ]; then
        run_make_step libfdt all
    fi
    run_make_step "$apxh_dir" all
    run_make_step "$hal_dir" all
    run_make_step "$plt_dir" all
    run_make_step libnux all
    run_make_step libnux_user all
    run_make_step tools all
    run_make_step example example_qemu
fi

[ -f "$kernel_elf" ] || die "kernel ELF not found: $kernel_elf (run --prepare first or use BUILD=...)"
[ -f "$user_elf" ] || die "user payload ELF not found: $user_elf (run --prepare first or use BUILD=...)"
[ -f "$apxh_elf" ] || die "APXH ELF not found: $apxh_elf (run --prepare first or use BUILD=...)"
[ -f "$example_img" ] || die "example_qemu image not found: $example_img (run --prepare first or use BUILD=...)"

write_gdb_cmds

note "prepared example image: $example_img"
note "kernel symbols: $kernel_elf"
note "user payload symbols: $user_elf"
note "APXH symbols: $apxh_elf"
note "QEMU debug command: (cd $builddir/example && make qemu_dbg)"
note "GDB command: $gdb_prog -x $gdb_cmds"

if [ "$run_qemu" -eq 1 ]; then
    note "qemu log: $qemu_log"
    note "running timeout --foreground ${TIMEOUT}s make qemu_dbg"
    set +e
    (cd "$builddir/example" && timeout --foreground "${TIMEOUT}s" make qemu_dbg >"$qemu_log" 2>&1)
    qemu_rc=$?
    set -e
    case "$qemu_rc" in
        0)
            note "QEMU exited with rc 0; see $qemu_log"
            ;;
        124)
            note "QEMU timed out after ${TIMEOUT}s while paused for GDB (-S -s); this is expected diagnostic evidence for --run-qemu"
            ;;
        *)
            tail -n 160 "$qemu_log" >&2 || true
            die "make qemu_dbg failed with rc $qemu_rc; see $qemu_log"
            ;;
    esac
fi

note "logs left in: $builddir"
