name: AMD64 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - name: Install i686 toolchain 
      run: sudo apt-get install gcc-i686-linux-gnu
    - name: bootstrap
      run: sh bootstrap.sh
    - name: configure
      run: ./configure ARCH=amd64 TOOLCHAIN=x86_64-linux-gnu TOOLCHAIN32=i686-linux-gnu
    - name: make
      run: make
   
